### ISSUE TITLE
Refactor `DB` type.

### ISSUE THREAD

**Issue by fisx** [liqd/thentos#225]
`Data.Map` is cool, but a bit low-level, and table indices or reference integrity (e.g. "every user id points to an existing user") are awkward to express.  Alternatives:

1. http://hackage.haskell.org/package/ixset-typed
2. http://hackage.haskell.org/package/tables

1. is probably easier to understand and use, 2. may be more feature complete / closer to what postgresql could do for us.

Both can be used to replace the three maps for active users with a single data structure that is much easier to keep consistent.  Ideally I would like to have three pull requests for this

1. a benchmark that causes lookup / change / delete / add operations on these three maps.
2.  one that repalces the three maps using ixset-typed.
3. one that replaces them using tables.

The resulting benchmarks would be interesting in their own right.

**Comment by fisx** [comment]
@ChristianSi, @fhartwig: I have some hope that this will answer many of your concerns with acid-state.  Let's see.  (-:

**Comment by ChristianSi** [comment]
Yeah, that looks promising...

**Comment by jkarni** [comment]
@fisx @ChristianSi @fhartwig This doesn't entirely address all issues with acid-state - access from  concurrent processes, sharding, cross-language interoperability, tooling, etc. Have we decided all that is okay? I just want to be sure before investing time that we in fact won't be throwing the work out.

**Comment by ChristianSi** [comment]
Good support of concurrency is of course a most, especially as we update our DB extremely frequently. Every lookup of an existing session pushes the session expire date into the future and therefore updates the DB. But I wouldn't put such ephemeral state as session expiry dates into an SQL table either, so that case might just require special treatment.

I wouldn't really worry about sharding and cross-language interoperability, I think the first will be overkill for us and the second might be nice to have, but I don't see a real use case.

**Comment by fhartwig** [comment]
I agree that this doesn't address most of the problems with acid-state, but I think it might still be worth doing. If we can avoid inconsistencies in our data with a reasonable amount of effort, that's a win. (Yes, a real dbms would be the "proper" solution, but the perfect is the enemy of the good and all that.). I also agree with Christian that we're unlikely to need/want sharding.

**Comment by fisx** [comment]
What is your estimate for this?  I would say maybe one day?

And yes, we won't throw out acid-state any time soon.  (Of course if anybody wants to attack this decision, please do so.)

**Comment by jkarni** [comment]
@fisx I might be slow, but my estimate is more than one day. Two, probably.

**Comment by jkarni** [comment]
OK, so I think `tables` is off the table, for reasons discussed elsewhere. `ixset-typed` is cool, but it doesn't enforce the constraint that certain indices be unique. (My brief investigations also didn't show any other packages that do precisely what we need.) So as I see it, we're left with enforcing constraints ourselves. The trade-off is between ensuring manually that any operation that modifies one map must modify the others accordingly (what we currently have), or ensuring that any insert or update checks that uniqueness constraints are not violated for all keys. 

My inclination is to have an opaque type (with multiple maps), and not export the constructor as a way of guaranteeing the invariants. But that really isn't very far from what we're currently doing (though our invariants are "enforced" by what transactions we provide on the DB). 

Anyone have any thoughts?

**Comment by fisx** [comment]
("elsewhere": https://github.com/ekmett/tables/issues/15, https://github.com/ekmett/tables/issues/33)

This all sounds plausible to me.  I guess it is ok to enforce explicit uniqueness in every transaction where it is required, but perhaps you can find a way to do that that makes it easier to detect if we missed it somewhere?  Perhaps a lens that lets you write to both, but only in an integrity-preserving way, and then un-import the lenses that don't?  I guess that's just introducing an abstract type as you suggested.

**Comment by ChristianSi** [comment]
My opinion is that if the Haskell packages cannot do it for us we should seriously consider switching to Postgres. Having constraints at the table level means that you'll get a runtime error if and when you screw up, while if we try do to it manually we lose that protection.

Having a constraint check at the end of each transaction is also not good enough since things can still go wrong within the transaction without being detected (e.g. an pre-existing value could accidentally be overwritten).

The other option besides Postgres might be to extend `ixset-typed` to support unique indexes, but I don't know how complicated that would be.

**Comment by fisx** [comment]
With the new info that we expect to have "MySQL or Oracle" as a requirement in the future, and a general sense that switching away from acid-state will get more expensive over time, we should probably close this ticket.  Anybody in favour?  Anything to add to this problem for documentation purposes, as it is of independent interest?

**Comment by fisx** [comment]
oh, and anybody please open and prioritize an issue "replace acid-state with suitable db backend".

**Comment by jkarni** [comment]
#268

**Comment by jkarni** [comment]
Closing this in favour of #268
