### ISSUE TITLE
Move to Postgres/MySql

### ISSUE THREAD

**Issue by jkarni** [liqd/thentos#268]
`MySql` is a listed option, and it sounds like `postgresql` is at least open to discussion. Ideally we'd write code that could be easy to modify so it works with either.

**Comment by fisx** [comment]
agreed.  i would be very sad if i came back in three weeks and we would be hooked to mysql.  postgresql should be the default!

**Comment by ChristianSi** [comment]
I suggested storing both confirmed and unconfirmed users in the same table because of our constraint that both email addresses and user names must be unique over *all* users, including unconfirmed ones. To conveniently enforce that we need a single table which might look something like this (using Postgres type names):

    CREATE TABLE user(
        us_id SERIAL NOT NULL,
        us_name TEXT UNIQUE NOT NULL,
        us_email TEXT UNIQUE NOT NULL,
        us_active BOOL NOT NULL,
        ...
        us_conf_token TEXT UNIQUE,
        us_expiry TIMESTAMP
    );

Also add a constraint enforcing that `us_conf_token` and `us_expiry` are NOT NULL if `us_active` is false (not-yet-activated user), and that they are NULL otherwise.

**Comment by ChristianSi** [comment]
A good practice I'd recommend adapting is to give all tables a `xx_modified` or  `xx_last_modified TIMESTAMP` field that is set to now whenever a row is inserted or updated.

**Comment by jkarni** [comment]
`user` is a reserved keyword in psql, so maybe `accounts`?

I still think we'd be doing extra work by keeping temporary accounts in the DB - if `expiry` means something like "should be removed from this table"). But I guess we're not going to try to actually expire entries...

**Comment by ChristianSi** [comment]
Maybe better generally use the plural for tables names, i.e. `users` or `accounts`. I have no strong preference on that but we should be consistent.

Temporary accounts will be deleted from the DB if they aren't confirmed before the expiry date, yes. At least that's what we currently do.

Regarding the "extra work", how to you suggest ensuring that emails are and stay unique if user information is spread across two different places and even, as I think you're suggestion, two different storage engines? I'm pretty sure that that'll involve extra work and, worse, that it'll be error-prone.

The disadvantage of the approach I suggest is that there will be will unassigned IDs since some users expire and their ID won't be re-used. But I don't see that as a problem, IDs aren't scarce. (If we suspect that most accounts will expire without being confirmed, we might use BIGSERIAL instead of SERIAL.)

**Comment by jkarni** [comment]
Ok, you might be right. We will have to have our own process for collecting expired accounts. Though psql's `notify` may come in handy here.

**Comment by jkarni** [comment]
http://stackoverflow.com/questions/26046816/is-there-a-way-to-set-an-expiry-time-after-wich-a-data-entry-is-automatically seems relevant

**Comment by ChristianSi** [comment]
Right now we delete expired entries manually from time to time (garbage collection function) so if we port that existing code to work on SQL tables we won't be any worse off than now. Alternatively we would use a Postgres trigger, yes, but I don't know you easy it's is to get the same functionality in MySql.

**Comment by fisx** [comment]
Closed due to #281.
