### ISSUE TITLE
Endpoints fall through

### ISSUE THREAD

**Issue by jkarni** [liqd/thentos#285]
When a path matches but the request body or content-type doesn't, the next endpoints get tried. This goes against the idea of preventing all requests under certain paths from going to the proxied service.

**Comment by ChristianSi** [comment]
My understanding was that that's a bug in Servant?

**Comment by jkarni** [comment]
The content-type stuff is, and I opened a ticket for it there. The request-body is less clear (I would say no), and we rely on the current behaviour in thentos.

**Comment by ChristianSi** [comment]
I'd say that if the request body is not parsable, Servant should respond with an error. At least, that's how it should be in our use case.

**Comment by ChristianSi** [comment]
This really is an extremely serious problem and needs to be fixed before we can even think of going live anywhere. Right now I work on A3 password reset (#168). As usual in proxy mode, we handle some endpoints ourselves and forward the request to A3. But if we cannot successfully parse a request body intended for one of our own endpoints (e.g. our FromJSON instance rejects a password because it's too short), then that endpoint is discarded and Servant instead calls the "catch-all" serviceProxy endpoint, thus forwarding the request to A3.

In that way, the A3 backend will see data it was never intended to see!

We cannot run the Thentos proxy in such a broken setup. Rather, all errors, no matter where they are thrown, **must** abort request processing and be reported to the user in the appropriate way.

Not only is this a show-stopper that makes actual deployment impossible, it also makes realistic testing of error situations impossible because the error will simply be discarded. This error must therefore be fixed with the utmost priority.

**Comment by fisx** [comment]
@ChristianSi: agreed, thanks for pinging this.  we'll look into it.

@jkarni: you said you opened a ticket "there".  do you mean haskell-servant/servant#41?  do you have time for this later today?

**Comment by fisx** [comment]
See aso: haskell-servant/servant#214

@ChristianSi, could you take a look at make sure the test cases model the behavior we need?  Did I miss anything?

**Comment by ChristianSi** [comment]
@fisx I replied there.

**Comment by jkarni** [comment]
Bad request done in #294.

**Comment by jkarni** [comment]
The overall picture is pretty [grim](https://github.com/haskell-servant/servant/pull/218). I don't think fixing all of this will be too hard, though.
