### ISSUE TITLE
security of email and username change in thentos-core

### ISSUE THREAD

**Issue by fisx** [liqd/thentos#311]
If a logged-in user changes her email address, the new email address must not be confirmed, but it is.

Possible solutions:

1. set unconfirmed-bit in user and invalidate the session token.  this would kick the user out of the system and force her to activate the user immediately.  if something goes wrong, the user will stay invalid.  not ideal from a UX perspective.
2. keep the old email address until the new one is validated, and leave the user logged-in.  not ideal from a security perspective: if the user has lost control over an email address to an identity thief, this makes it hard to switch it off.

I still like 2 best from all the options I can think of.

**Comment by jkarni** [comment]
> this makes it hard to switch it off.

Why hard? They just need to check their (new) email.

**Comment by fisx** [comment]
> Why hard? They just need to check their (new) email.

Fair enough.  I think what I meant is that it's bad if something goes wrong there.  Unirregardless, 2. is my favourite.  (:

**Comment by jkarni** [comment]
:+1: on 2

**Comment by jkarni** [comment]
Looking at the code, (2) seems to be already what's happening. And I tried the interface out, which bears out this reading. Am I missing something?

**Comment by jkarni** [comment]
Aha, I see. Is the issue that the email confirmation is being sent to the wrong (old) email address?

Often websites will require that changes go via the email because that's considered safer than the session, so there's some reason to send it to the old email address. On the other hand, yes, this doesn't guarantee that the user actually typed in the right email and has access to it.

**Comment by jkarni** [comment]
Recap of discussion elsewhere. There are currently two completely independent ways of changing the email (and the password). One (which is what the frontend actually uses), does proper verification via email etc. The other, `updateUserField[s]`, does not. The latter should probably be removed, but it's currently still necessary for updating emails when A3 itself does the change. There are difficulties in making all changes of password and email come from thentos (rather than A3), which we should further discuss, in order to decide whether we can in fact remove `updateUserField`.

**Comment by fisx** [comment]
Also, `Thentos.Backend.Api.Simple` uses `updateUserField` for email and user name update.  This needs to be cleaned up as well.

Right now I am leaning towards leaving adhocracy in charge of these things and focus on fulfilling requirements rather than cleaning up the code, but let's talk this through on Monday.

**Comment by fisx** [comment]
On second thoughts: the point of thentos is that the user is kept secret from adhocracy, and only the persona names are exposed, so handling email should really be handled by thentos as well.

There are two levels of security here: (1) the users who visit adhocracy should not be able to see private user data; and (2) the admin running adhocracy should not be able to do that.  (1) can be achieved without thentos, so our goal is clearly (2).  But even (1) is much easier to achieve if we never pass the secret information to adhocracy in the first place, rather than counting on adhocracy keeping it secret for us.

**Comment by ChristianSi** [comment]
@jkarni:

> The latter should probably be removed, but it's currently still necessary for updating emails when A3 itself does the change.

Actually that's not an issue, as A3 doesn't allow changing the email, AFAIK.

**Comment by ChristianSi** [comment]
@fisx Moving emails out of A3 would be a completely different change, and a pretty big one, because currently all the email templates are configured in A3.
