### ISSUE TITLE
Add personas to DB

### ISSUE THREAD

**Issue by ChristianSi** [liqd/thentos#318]
A persona belongs to a user and one or multiple services (= processes). A user may have at most one persona per process. (Note: the latter requirement may be relaxed in the future).

**Comment by fisx** [comment]
[just adding my own, disorganized thoughts]

- I think this means service needs a field `uri_prefix` (or `uri`, but implicitly still meaning "prefix).  If a new process in created on a3, the corresponding new service is created.
- We need to communicate to a3 that services are identified by URI prefices, which means that all resources semantically living in a process need to have paths with its prefix.
- What would it mean for one service to have several prefices?  What if some prefices are shared by several services?  It may both be a bad idea, but perhaps it would be worth writing down a compelling reason why somewhere in the code.  (I suggesting to clutter the documentation, again.  Ignore me.  :-)

**Comment by fisx** [comment]
A few more points [@ChristianSi, is this the right place to dump them?  If not, any suggestions?]

- Thentos needs to maintain individual adhocracy session tokens per persona, otherwise two personas can be linked when using the same session token.  This could be done by applying a suitable one-way function to the thentos session token (whould "hash thentos session token and persona" work?), or we could maintain yet another table.
- What do batch requests do to the idea of chosing a persona based on the request url?  Batch requests have many URLs, which may belong to different processes (at least in theory).  One solution would be to take batch requests apart in the proxy, and re-assemble the responses on the way back.  Not pretty, though.
- A3 has an admin role and a rest end-point where we can just put new / changed users and do not have to worry about the qualification process at all (even less than now?).  Not sure if we need it, but it may make things simpler.

**Comment by ChristianSi** [comment]
@fisx I'd say it's not the right place, functional requirements must be specified as part of the user story, while tickets are about how to implement them. Tickets may request technical requirements, the the functional requirements must come from the story. Also, functional requirements shouldn't be added after a story is in process -- though in this case it's a bit of a problem that the story doesn't contain any explicit requirements ;)

Re 1: that's not a problem, since A3 never sees any session tokens, all the get from us as identifying information is the persona name (user name from A3's viewpoint).

Re the rest: let's talk that through...

**Comment by ChristianSi** [comment]
Re 2 (after talking): It's unclear whether we need that at all (I'm very skeptical) and it's definitively not part of this story.

Re 3: that's not a requirement, but good to know -- might come handy.

**Comment by fisx** [comment]
Ok, I think that concludes my yesterday's comment.  I added 2. to https://tree.taiga.io/project/fisx-thentos/us/3 for further discussion.
