### ISSUE TITLE
We cannot rely on the a3 backend API living at /

### ISSUE THREAD

**Issue by fhartwig** [liqd/thentos#411]
There are places in our code that seem to rely on the fact that the A3 backend is at the root path of some domain (e.g. `http://example.com/`). Unfortunately, a3 can apparently deployed in such a way that it lives under some path prefix (e.g. all backend URLs start with `http://example.com/api/`).
An example of this problem is https://github.com/liqd/thentos/blob/1c59b927b871114f067b48e930bdf51067d4a154/thentos-adhocracy/src/Thentos/Adhocracy3/Backend/Api/Simple.hs#L626 , unless I'm missing something.

**Comment by ChristianSi** [comment]
`userIdFromPath` is no longer used, except in the outdated `resetPassword` implementation that needs to be rewritten anyway (see #321). But this is still an issue because of the way how URLs are stored in the config. Here's how it looks on the outside:

    proxy:
        service_id: qlX4MP7xEgtRng+8iNvMIcSo
        endpoint: http://localhost:6541

This could easily be changed to e.g.:

    proxy:
        service_id: qlX4MP7xEgtRng+8iNvMIcSo
        endpoint: http://localhost:6541/api

However, that would currently cause an error when reading the config, because "endpoint" is a `ProxyUri`:

    ProxyUri { proxyHost :: SBS
             , proxyPort :: Int
             , proxyPath :: SBS
             }

My personal opinion is that `ProxyUri` should die and we should just use `Uri` instead.

I suppose that no further changes would be necessary so the issue would be easy to fix. However, we would of course have to retest everything to make sure that's indeed the case.

**Comment by ChristianSi** [comment]
Actually, I suspect that everything works already since `ProxyUri` already has an `proxyPath` component that's sufficient to handle such cases. (It didn't initially.) I'll check whether the Thentos proxy and A3 play together when using a path prefix for the latter. If yes, I'll close this issue.

**Comment by ChristianSi** [comment]
I wasn't able to test this fully, since it doesn't seem to be possible to define such a prefix in the A3 config (I guess that request forwarding via Nginx or similar is needed to use it). However, setting `endpoint: http://localhost:6541/api` will certainly forward those requests not directly handled by Thentos in the expected way (e.g. `THENTOS-URL/blah` is forwarded to `http://localhost:6541/api/blah`, while `THENTOS-URL/login_username` is still handled by Thentos itself).
